import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CSO D.I.M.S.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-dvh overflow-hidden`}>

        {children}

        {/* Toaster */}
        <div className="absolute">
          <Toaster
            richColors
            position='bottom-right'

          />
        </div>
      </body>
    </html>
  );
}
